apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: fashion-mnist
  namespace: default
spec:
  name: seldon
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/tfserving-proxy_rest:1.3.0
          name: tfserving-proxy
          resources:
            requests:
              cpu: "0.5"
        - args:
          - /usr/bin/tensorflow_model_server
          - --rest_api_port=8501
          - --port=7001
          - --model_name=fashion-mnist
          - --model_base_path=/mnt/fashion-mnist-models
          image: tensorflow/serving:2.3.0
          name: tfserving-cpu
          ports:
          - containerPort: 7001
            protocol: TCP
          - containerPort: 8501
            protocol: TCP
          securityContext:
            runAsUser: 1000
          volumeMounts:
          - mountPath: /mnt
            name: model-storage
        terminationGracePeriodSeconds: 1
        volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: mnist-cos-pvc
    graph:
      children: []
      endpoint:
        type: REST
      name: tfserving-proxy
      parameters:
      - name: rest_endpoint
        type: STRING
        value: http://0.0.0.0:8501
      - name: model_name
        type: STRING
        value: fashion-mnist
      - name: signature_name
        type: STRING
        value: serving_default
      type: MODEL
    name: predictor
    replicas: 1
  replicas: 1
  