apiVersion: v1
kind: PersistentVolume
metadata:
  name: mnist-cos-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Gi
  csi:
    driver: com.tencent.cloud.csi.cosfs
    volumeAttributes:
      additional_args: -oallow_other -odbglevel=err
      bucket: rdmatest-1251707795
      path: /
      url: http://cos.ap-shanghai.myqcloud.com
    volumeHandle: rdmatest-1251707795
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
